# Generated by Django 4.1 on 2022-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultora_app', '0002_alter_programmer_program_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='nick',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
