# Generated by Django 4.1 on 2022-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultora_app', '0004_alter_programmer_program_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='nick',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='program_lang',
            field=models.CharField(choices=[('js', 'Javascript'), ('python', 'Python'), ('c', 'C'), ('java', 'Java'), ('php', 'PHP')], max_length=32),
        ),
    ]
